### ISSUE TITLE
ServiceMonitor

### ISSUE THREAD

**Issue by gattma** [gepaplexx/baukasten#4]
siehe 
https://console.apps.play.gepaplexx.com/k8s/cluster/customresourcedefinitions/servicemonitors.monitoring.coreos.com/instances
und 
https://docs.openshift.com/container-platform/4.8/monitoring/managing-metrics.html#specifying-how-a-service-is-monitored_managing-metrics

Beispiel:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scraping-mega-backend
  namespace: mega-backend
spec:
  endpoints:
    - interval: 30s
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: mega-backend
```
